language: node_js
node_js:
- 8
before_install:
- openssl aes-256-cbc -K $encrypted_9e5b9e749475_key -iv $encrypted_9e5b9e749475_iv
  -in id_rsa.enc -out id_rsa -d
- cd public
install:
- npm install
before_script:
- cd public
script:
- npm run build
- npm test
after_success:
- if [ "$TRAVIS_PULL_REQUEST" == false ]; then 
    ssh 198.199.116.198;
  fi
notifications:
  email: false
branches:
  only:
  - master
