language: node_js
node_js:
  - 8
before_install:
  - cd public
install:
  - npm install
before_script:
  - cd public
script:
  - npm run build
  - npm test
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master "]]; then 
      echo it works ;
    fi
notifications:
  email: false