language: node_js
node_js:
- 8
addons:
  ssh_known_hosts: 
  - 198.199.116.198
before_install:
- openssl aes-256-cbc -K $encrypted_9e5b9e749475_key -iv $encrypted_9e5b9e749475_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 600 id_rsa
- mv id_rsa ~/.ssh/id_rsa
- cd public
install:
- npm install
before_script:
- cd public
script:
- npm run build
- npm test
after_success:
- if [ "$TRAVIS_PULL_REQUEST" == false ]; then 
    ssh deploy@198.199.116.198 'bash -s' < ~/deploy.sh
  fi
notifications:
  email: false
branches:
  only:
  - master
